name: reccomandations_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.0.0+5
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.8.0
  firebase_auth: ^0.16.1
  strings: ^0.1.2
  provider: ^4.1.2
  filter_list: ^0.0.4
  google_fonts: ^1.1.0
  material_design_icons_flutter: ^4.0.5345
  fluttertoast: ^4.0.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  fonts:
    - family: OpenSans
      fonts:
        - asset: OpenSans/OpenSans-Bold.ttf
          weight: 700

        - asset: OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: OpenSans/OpenSans-ExtraBold.ttf
          weight: 800

        - asset: OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
          style: italic

        - asset: OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic

        - asset: OpenSans/OpenSans-Light.ttf
          weight: 300

        - asset: OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: OpenSans/OpenSans-LightItalic.ttf
          weight: 400

        - asset: OpenSans/OpenSans-SemiBold.ttf
          weight: 600

        - asset: OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic